### ISSUE TITLE
Upgrade to the latest Facebook SDK

### ISSUE THREAD

**Issue by aggutkarsh** [saadfarhan124/flutter_facebook_sdk#13]
Please upgrade the Android & iOS Facebook SDK to their latest version, i.e., 12.2

**Comment by alectogeek** [comment]
@saadfarhan124
Is this package abandoned?

**Comment by Tetsukick** [comment]
I m also facing same issue. plase upgrade SDK version

**Comment by Tetsukick** [comment]
@aggutkarsh 
I fixed this issue.
I m waiting merge my PR 
https://github.com/saadfarhan124/flutter_facebook_sdk/pull/14

but if you want to use it, you can use like below

in pubspec.yaml

```
  flutter_facebook_sdk:
    git:
      url: git://github.com/Tetsukick/flutter_facebook_sdk
      ref: master
```
